import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Barres latérales du site.
 *
 * CHOIX D'ARCHITECTURE : on utilise `autogenerated`, c'est-à-dire que la
 * navigation est déduite de l'arborescence des fichiers.
 *
 * Pourquoi ? Parce qu'une formation de plus de 20 modules va évoluer en
 * permanence. Maintenir à la main une liste de 200 entrées garantit un
 * décalage entre le sommaire et le contenu réel. Ici, créer un fichier
 * SUFFIT à le faire apparaître au bon endroit.
 *
 * L'ordre et les titres sont pilotés par :
 *   - le préfixe numérique des dossiers (`00-demarrer`, `01-fondations`…) ;
 *   - le champ `sidebar_position` du front matter de chaque page ;
 *   - les fichiers `_category_.json` pour les libellés de section.
 */
const sidebars: SidebarsConfig = {
  cours: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
